[package]
name = "idlc_ast"
version = "0.1.0"
edition = "2021"
authors = [ "Arvind Mukund<arvimuku@quicinc.com" ]
description = "AST structure for IDL; contains grammar and AST generators"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.2"
pest_derive = "2.7.2"
thiserror = "1.0.47"
