[package]
name = "idlc_ast"
version = "0.1.0"
edition = "2021"
authors = [ "Arvind Mukund<arvimuku@quicinc.com" ]
description = "AST structure for IDL; contains grammar and AST generators"

[[bin]]
name = "idlc_ast"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
pest = "2.7.1"
pest_derive = "2.7.1"
petgraph = "0.6.3"
thiserror = "1.0.44"

