use idlc_mir::Node;

use crate::{
    globals::{emit_const, emit_include, emit_struct},
    interface::{emit_interface_impl, emit_interface_invoke},
};

pub struct Generator;

impl idlc_codegen::SplitInvokeGenerator for Generator {
    fn generate_implementation(mir: &idlc_mir::Mir) -> String {
        let mut result = String::new();
        result.push_str(&generate_common());

        for node in &mir.nodes {
            match node.as_ref() {
                Node::Include(i) => {
                    result.push_str(&emit_include(i));
                }
                Node::Const(c) => {
                    result.push_str(&emit_const(c));
                }
                Node::Struct(s) => {
                    result.push_str(&emit_struct(s.as_ref()));
                }
                Node::Interface(i) => {
                    result.push_str(&emit_interface_impl(i));
                }
            }
        }

        result
    }

    fn generate_invoke(mir: &idlc_mir::Mir) -> String {
        let mut result = generate_common();

        let input_name = &mir.tag.file_stem().unwrap().to_str().unwrap();
        result.push_str(&format!("#include \"{}.h\"\n\n", input_name));

        for node in &mir.nodes {
            match node.as_ref() {
                Node::Include(i) => {
                    result.push_str(&emit_include(i));
                }
                Node::Interface(i) => {
                    result.push_str(&emit_interface_invoke(i));
                }
                _ => (),
            }
        }

        result
    }
}

fn generate_common() -> String {
    r#"#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

"#
    .to_string()
}
