[package]
name = "idlc_codegen"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idlc_mir = { version = "0.1.0", path = "../idlc_mir" }
